# This is the config file for building http-cpp and running its autotest suite with Travis-ci.org

language: cpp

compiler:
  - gcc
#  - clang

env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "eWcN2qlC7yua+8Iqsbut6r6pspMUuQLXzPa+6CdfK2KSDsGBZg1m6opoq0i8krURoc+0jldrmIB+oJz3ABllgzwn6+q9NGwasmAjo+6+V2CKNgW2tBB5L8bMnaFkBlPW4pToVyLV6os+er7lW67psdKwXc6kpFgDnrZxhlp+Etw="
env:
  - BUILD_CONFIG=Debug
  - BUILD_CONFIG=Release

addons:
  coverity_scan:
    project:
      name: "Kosta-Github/http-cpp"
      description: "Provide a simple and portable interface to do HTTP requests in C++."
    notification_email: github@ks-baumann.de
    build_command_prepend:
    build_command:
    branch_pattern: coverity_scan

before_install:
  # update fit submodules (if required)
  - git submodule update --init --recursive

  # update the apt repository
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ saucy main universe"
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ raring main universe"
  - sudo add-apt-repository -y "deb http://llvm.org/apt/raring/ llvm-toolchain-raring main"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq libcurl3
  - sudo apt-get install -qq nodejs
  - if [ "$CXX" = "g++"     ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++"     ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq clang-3.4; fi

install:
  - set
  - export
  - echo CXX=$CXX
  - $CXX --version
  - cmake --version
  - cmake -H. -BBuild -DCMAKE_BUILD_TYPE=$BUILD_CONFIG

script:
  - cd Build && make -k && ctest -V --timeout 60 && cd ..
