language: cpp

compiler:
  - gcc

env:
  global:
    # coverity scan environment
    - secure: "PUidMNLocRlMRcZjYa59oxKLGTmXtjB5N77k6zijoO4bDy6rKxLhVOUI94QtriOyIJdGzeqHx1aW1M0S1TR8hv2zf+U/wl3zwk7lvDvuVRvyaxUw732aEa2BmJ5i8P1Y9iIKwunARWo4EgT7DeJdleBjg88oNkekq0GQEN1yf90="
  matrix:
    - BUILD_CONFIG=Debug

before_install:
  # pull in some common scripts for setting up Travis CI build environment
  - git clone --depth=1 https://github.com/Kosta-Github/travis-setup.git
  - sudo travis-setup/update-environment.sh
  - sudo travis-setup/update-gcc-latest.sh

  # update some required packages
  - sudo apt-get install -qq libcurl3
  - sudo apt-get install -qq nodejs
  
install:
  - if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIG ; fi

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then make -k && ctest -V --timeout 60 ; fi

addons:
  coverity_scan:
    project:
      name: "Kosta-Github/http-cpp"
      description: "https://github.com/Kosta-Github/http-cpp"
    notification_email: github@ks-baumann.de
    build_command_prepend: "cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIG"
    build_command: "make"
    branch_pattern: coverity
